# SignStream-RVQ Default Configuration
experiment_name: "Baseline-Test002"
save_path: "./checkpoints"

data:
  root: "/workspace/data/data_lc/slr_rvq/CSL-Daily" 
  split_file: "/workspace/data/data_lc/slr_rvq/CSL-Daily/split_files.json"  # Optional split file
  fps: 30
  chunk_len: 10
  max_seq_len: 1000  # Maximum sequence length in frames
  normalize:
    center_parts: true
    bbox_range: 8
    eye_distance_norm: true
  body_parts:
    face: [24, 91]
    left_hand: [92, 112] 
    right_hand: [113, 133]
    body: [1, 17]
    full_body: [1, 133]
  center_indices:
    body: 1
    face: 32
    left_hand: 92
    right_hand: 113
  augment:
    mirror: true
    mirror_prob: 0.5
    time_warp: true
    time_warp_factor: 0.1
    dropout_prob: 0.05
    confidence_threshold: 0.25

model:
  encoder_layer: 2
  latent_dim: 256
  type_embed_dim: 16
  arch: "transformer"  # mlp or transformer
  dropout: 0.1
  temporal_aggregation: "mean"  # mean, max, attention
  rvq:
    levels: 3
    codebook_size: 1024
    ema_decay: 0.99
    commitment_beta: 0.1  # Reduced for stability
    usage_reg: 0.0001  # Reduced for stability
    temporal_loss_alpha: 0.0  # Disabled for stability (set to 0.01-0.05 to enable)
    enable_temporal_loss: false  # Master switch for temporal loss
    # Weighted loss configuration for 5D data (x, y, conf, vx, vy)
    position_weight: 1.0  # Weight for position loss (x, y)
    velocity_weight: 0.1  # Weight for velocity loss (vx, vy) - lower to prevent explosion

training:
  epochs: 200
  batch_size: 8
  lr: 0.0001  # Reduced learning rate for stability
  wd: 0.01
  amp: "fp32"  # fp32, fp16, bf16
  log_wandb: false
  seed: 42
  save_every: 5
  eval_every: 1
  sample_every: 5  # Sample tokens every N epochs
  num_eval_samples: 5
  # Stability parameters
  max_grad_norm: 2.0  # Gradient clipping
  loss_scale_factor: 0.1  # Scale loss to prevent explosion

logging:
  use_tensorboard: true
  log_dir: "./logs"
  log_level: "INFO"

export:
  enable_rle: true
  rle_threshold: 0.02  # Threshold for no-change detection
